type ExampleReportSummary = {
  url: string;
  score: number;
  scoreLabel: string;
  readiness: string;
  verdict: string;
  note: string;
};

type ExampleReportEvidence = {
  title: string;
  h1: string;
  h2sFirstFive: string[];
  schemaTypes: string[];
  contactEvidence: string;
  faqSignals: {
    explicit: boolean;
    indirectLinks: number;
    directAnswerSnippets: number;
  };
};

type ExampleReportSnapshotDiagnostics = {
  httpStatus: number;
  contentType: string;
  bytesReceived: number;
  snapshotQuality: string;
  fetchTimestamp: string;
};

type ExampleReportInterpretation = {
  type: "strength" | "weakness" | "neutral";
  category: string;
  statement: string;
};

type ExampleReportFix = {
  priority: string;
  action: string;
};

type ExampleReportMetadata = {
  reportId: string;
  domain: string;
  brandGuessed: string;
  pageEvaluated: string;
  evaluatedUrl: string;
  fetchTimestamp: string;
  generatedAt: string;
  defaultAnswerVersion: string;
  scoringEngine: string;
  promptPack: string;
};

type ExampleReportScoreCheck = {
  label: string;
  score: number;
  max: number;
  evidence: string;
};

type ExampleReportCategory = {
  score: number;
  max: number;
  checks: ExampleReportScoreCheck[];
};

type ExampleReportData = {
  summary: ExampleReportSummary;
  scoreBreakdown: {
    entityClarity: ExampleReportCategory;
    structuralComprehension: ExampleReportCategory;
    answerabilitySignals: ExampleReportCategory;
    trustAndLegitimacy: ExampleReportCategory;
    commercialClarity: ExampleReportCategory;
  };
  evidence: ExampleReportEvidence;
  snapshotDiagnostics: ExampleReportSnapshotDiagnostics;
  aiInterpretation: ExampleReportInterpretation[];
  fixPlan14Day: ExampleReportFix[];
  metadata: ExampleReportMetadata;
  footer: string;
};

type ExampleReportContext = {
  isExample: boolean;
  disclosureTitle: string;
  disclosureText: string;
  summaryNoteOverride: string;
  footerOverride: string;
};

export const exampleReportContext: ExampleReportContext = {
  isExample: true,
  disclosureTitle: "Example Report",
  disclosureText:
    "This is a public DefaultAnswer report generated for defaultanswer.com using the same methodology applied to all sites.",
  summaryNoteOverride: "No critical fixes detected — remaining improvements are marginal.",
  footerOverride: "Generated by DefaultAnswer v1.12 — LLM Recommendation Intelligence",
};

export type { ExampleReportContext, ExampleReportData };
